### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by HuangQinJian** [limit-scu/2019-ICML-COMIC#1]
Could you provide all the datatset used in paper?Thanks!

**Comment by Three-year-old** [comment]
I got an error "TypeError: Expecting matrix here" where I run the demo.py. Is there anything wrong with the dataset "Caltech101-20.mat"? Has anyone encountered this problem？

Traceback (most recent call last):
  File "E:/experiment/2019-ICML-COMIC/COMIC-release/code/demo.py", line 9, in <module>
    X_list, Y = load_data(data_name)
  File "E:\experiment\2019-ICML-COMIC\COMIC-release\code\data.py", line 11, in load_data
    mat = sio.loadmat(data_dir)
  File "E:\experiment\2019-ICML-COMIC\venv\lib\site-packages\scipy\io\matlab\mio.py", line 208, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "E:\experiment\2019-ICML-COMIC\venv\lib\site-packages\scipy\io\matlab\mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "E:\experiment\2019-ICML-COMIC\venv\lib\site-packages\scipy\io\matlab\mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 675, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 721, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 894, in scipy.io.matlab.mio5_utils.VarReader5.read_cells
  File "mio5_utils.pyx", line 666, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
TypeError: Expecting matrix here

Process finished with exit code 1

**Comment by dugzzuli** [comment]
There are some unknown errors in the dataset "Caltech101-20" provided by this depository. You need to look at datasets from other places, such as "https://github.com/youweiliang/Multi-view_Graph_Learning".
