### ISSUE TITLE
代码运行不出结果

### ISSUE THREAD

**Issue by zhangyuanyang21** [limit-scu/2019-ICML-COMIC#6]
你好，配置好环境安装好包，后运行python demo.py，请问为啥代码没有运行呢？

**Comment by zhangyuanyang21** [comment]
请问运行代码后出现
C:\Users\666\.conda\envs\comic\python.exe D:\soft\PyCharmCommunity\plugins\python-ce\helpers\pydev\pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 12731 --file D:/download/对比实验/2019-ICML-COMIC-master/COMIC-release/code/demo.py
Connected to pydev debugger (build 221.5921.27)
Traceback (most recent call last):
  File "D:\soft\PyCharmCommunity\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/download/�Ա�ʵ��/2019-ICML-COMIC-master/COMIC-release/code/demo.py", line 14, in <module>
    X_list, Y = load_data(data_name)
  File "D:\download\�Ա�ʵ��\2019-ICML-COMIC-master\COMIC-release\code\data.py", line 9, in load_data
    mat = sio.loadmat(data_dir)
  File "C:\Users\666\.conda\envs\comic\lib\site-packages\scipy\io\matlab\mio.py", line 208, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "C:\Users\666\.conda\envs\comic\lib\site-packages\scipy\io\matlab\mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "C:\Users\666\.conda\envs\comic\lib\site-packages\scipy\io\matlab\mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 675, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 721, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 894, in scipy.io.matlab.mio5_utils.VarReader5.read_cells
  File "mio5_utils.pyx", line 666, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
TypeError: Expecting matrix here
python-BaseException
怎么解决呢？
